### ISSUE TITLE
Process exited with status 1

### ISSUE THREAD

**Issue by ZhangTianrong** [wsvn53/scrcpy-ios#12]
I have tried a number of servers including Windows machine, DD-WRT router and the android device itself (with ubuntu installed through linux deploy). The Windows machine can scrcpy into the android device and the other devices can at least run adb shell. Every time I press connect, it fails with "Process exited with status 1". I am using iPad with iOS 15 and I have the v2.2 ipa installed through Sideloadly. The permission to access local network is granted. I guess if the ssh is successful, there will be some command in `bash_history` but there is none. By the way, when I tap on the three dots on the top right corner, the app exits. Is this the supposed behavior?

**Comment by wsvn53** [comment]
[Scrcpy.ipa.zip](https://github.com/wsvn53/scrcpy-ios/files/7813242/Scrcpy.ipa.zip)

Can you try to install this ipa, and try again. Pls paste the logs to here by click top-right corner "..." and then "Show Scrcpy Logs".

**Comment by ZhangTianrong** [comment]
I would love to, but when I tap on the 3 dots, the app crashes immediately.

**Comment by wsvn53** [comment]
Can you connect your iPad with mac, and open Console.app to locate the crash logs when you tap the 3 dots?

**Comment by ZhangTianrong** [comment]
Please find the log [here](https://1drv.ms/u/s!Ah7B82t6Uj6F50J3rrKbUS_Iv7Ha?e=1DutvR). I only kept the lines with `scrcpy`.

**Comment by wsvn53** [comment]
Thanks, I've fixed this crash. Can you try to install the ner version in the attachment and try to paste the scrcpy logs here.
[Scrcpy.ipa.zip](https://github.com/wsvn53/scrcpy-ios/files/7818999/Scrcpy.ipa.zip)

**Comment by ZhangTianrong** [comment]
Here it is.

```
DEBUG: Device serial: 192.168.1.133:5555
DEBUG: Screensaver enabled
DEBUG: Using server: $TMPDIR/share/scrcpy/scrcpy-server
RET> Upload [/private/var/containers/Bundle/Application/8556C18B-B6DF-4A7D-ADF7-FACA944348CA/Scrcpy.app/scrcpy-server] => [$TMPDIR/share/scrcpy/scrcpy-server] (NO)
ERROR: Server connection failed
Scrcpy STOPPED.
ACTION> Show Scrcpy Logs
```

Seems unable to connect to ssh server. There might still be some issue with local network? By the way, when it connects, are we supposed to declare `TMPDIR` in `.bashrc` for this to work?

**Comment by wsvn53** [comment]
It seems upload scrcpy-server to remote ssh server failed, can you try to run the following command and paste output here?

```sh
ssh [YourUser]@[YourSSH Server] 'echo $TMPDIR/share/scrcpy/scrcpy-server && ls -la $TMPDIR/share || echo $TMPDIR'
```

**Comment by ZhangTianrong** [comment]
It says 

```
/share/scrcpy/scrcpy-server
ls: cannot access '/share': No such file or directory
```
but I have added `export TMPDIR=/home/[username]/.local/tmp` to `bashrc` and the login shell for this user is indeed `/bin/bash`.

I looked at the `uploadFile` function and tried the command `[ -d "$TMPDIR/share/scrcpy" ] || mkdir -pv "$TMPDIR/share/scrcpy"; cat > "$TMPDIR/share/scrcpy/scrcpy-server"` in the remote machine and it does stores stdin into the desired file without a problem. Could it be the `gossh` is logged in through some other shell and bypassed my `bashrc`? I remember seeing an issue calling for customization `scrcpy-server` location, maybe that is going to make life much easier?

However, when I looked at `ssh` package, it seems that if the command runs but got a non-zero exit state or no exit state, the error should not be "Server connection failed"? (I am not familiar with `go` and actually I didn't see this error message defined anywhere).

**Comment by wsvn53** [comment]
Thanks for your logs, I have changed logic to import bashrc or zshrc before upload file, can you try this version again.
[Scrcpy.ipa.zip](https://github.com/wsvn53/scrcpy-ios/files/7819654/Scrcpy.ipa.zip)

**Comment by wsvn53** [comment]
> It says
> 
> ```
> /share/scrcpy/scrcpy-server
> ls: cannot access '/share': No such file or directory
> ```
> 
> but I have added `export TMPDIR=/home/[username]/.local/tmp` to `bashrc` and the login shell for this user is indeed `/bin/bash`.
> 
> I looked at the `uploadFile` function and tried the command `[ -d "$TMPDIR/share/scrcpy" ] || mkdir -pv "$TMPDIR/share/scrcpy"; cat > "$TMPDIR/share/scrcpy/scrcpy-server"` in the remote machine and it does stores stdin into the desired file without a problem. Could it be the `gossh` is logged in through some other shell and bypassed my `bashrc`? I remember seeing an issue calling for customization `scrcpy-server` location, maybe that is going to make life much easier?
> 
> However, when I looked at `ssh` package, it seems that if the command runs but got a non-zero exit state or no exit state, the error should not be "Server connection failed"? (I am not familiar with `go` and actually I didn't see this error message defined anywhere).

The reason for this issue is that ssh execute is not running in login mode, so it does not read bashrc or zshrc, which has the same effect as your direct `ssh x@x 'some command'`, currently it adds the logic of import profile to adb related commands and ignores uploadFile, after adding it should solve the TMPDIR issue.

Yes, allow customization the scrcpy server path is a good suggestion, I'll add it in future version.

**Comment by ZhangTianrong** [comment]
Still failing to upload. Which bashrc are you loading? I have tried both /etc/bash.bashrc and /home/[username]/.bashrc but neither worked. TMPDIR isn’t necessarily defined in many distros, if you can read the output of the command execution, how about calling mktemp -d to create and determine the temp folder?

**Comment by wsvn53** [comment]
Can you tell me what system your ssh server is on? I think I'd better create an server environment to test the same as yours.

**Comment by ZhangTianrong** [comment]
It's a Ubuntu 18 (armhf) installed on the target (rooted) android device with Linux Deploy. I also was trying to use DD-WRT or Windows device before this but now that I know this app depends on specific commands to run through SSH, they might be less relevant, e.g. Windows has a different convention for paths and there is no bash script support. Perhaps DD-WRT should be able to work. The reason I choose them as server is because they are devices that are always on in my household.

**Comment by wsvn53** [comment]
[Scrcpy.ipa.zip](https://github.com/wsvn53/scrcpy-ios/files/7822940/Scrcpy.ipa.zip)
How about this ipa, I just add some trick to get TMPDIR as following:

```sh
PROFILE=~/.$(basename $SHELL)rc; 
[ -f /etc/profile ] && . /etc/profile;
[ -f $PROFILE ] && . $PROFILE; 
[ -z $TMPDIR ] && export TMPDIR=$(dirname $(mktemp -d));
```

But I'm not sure it works, so if you still occur errors, try to run this command that I can check the ssh detail envirement:

```sh
ssh [user]@[host] 'export'
```

**Comment by ZhangTianrong** [comment]
Much more progress now. The upload is successful but there are still errors.

```
DEBUG: Screensaver enabled
DEBUG: Device serial: 127.0.0.1:5555
DEBUG: Using server: $TMPDIR/share/scrcpy/scrcpy-server
RET> Upload [/private/var/containers/Bundle/Application/CEB564D0-5BF1-4B70-915B-2A8315CB8893/Scrcpy.app/scrcpy-server] => [$TMPDIR/share/scrcpy/scrcpy-server] (YES)
CMD> adb -s 127.0.0.1:5555 push $TMPDIR/share/scrcpy/scrcpy-server /data/local/tmp/scrcpy-server.jar
RET> [adb -s 127.0.0.1:5555 push $TMPDIR/share/scrcpy/scrcpy-server /data/local/tmp/scrcpy-server.jar] (1)
CMD> adb -s 127.0.0.1:5555 reverse localabstract:scrcpy tcp:27183
RET> [adb -s 127.0.0.1:5555 reverse localabstract:scrcpy tcp:27183] (1)
CMD> adb -s 127.0.0.1:5555 shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.21 log_level=debug bit_rate=3000000 max_fps=60
CMD> adb -s 127.0.0.1:5555 reverse --remove localabstract:scrcpy
RET> [adb -s 127.0.0.1:5555 reverse --remove localabstract:scrcpy] (1)
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: metal
DEBUG: Trilinear filtering disabled (not an OpenGL renderer)
DEBUG: Using icon: $TMPDIR/share/icons/hicolor/256x256/apps/scrcpy.png
ERROR: Could not open image codec: $TMPDIR/share/icons/hicolor/256x256/apps/scrcpy.png
WARN: Could not load icon
INFO: Initial texture: 1920x1080
DEBUG: Switched to fullscreen mode
DEBUG: Starting stream thread
Hello scrcpy v1.21
ACTION> Show Scrcpy Logs
```

The app crashes instantly.

I can see the`scrcpy-server` at the desired location but there is no icons folder alongside. Is the upload file a tar ball and supposed to be unpacked?

**Comment by wsvn53** [comment]
You can ignore the `icon can not found` error, that is used for desktop version of scrcpy, for iOS we dont need that. 

So, can you see the Android screen finally? I cant see any other errors from you logs above.

**Comment by ZhangTianrong** [comment]
No, the app crashes instantly. Maybe I need to go back to syslog?

Edit: You can find the log from the same link I used before.

**Comment by wsvn53** [comment]
> No, the app crashes instantly. Maybe I need to go back to syslog?
> 
> Edit: You can find the log from the same link I used before.

No, I cant locate the detailed crash logs. If you have Xcode installed, you can open menu "Window" -> "Devices and Simulators" -> "Choose Device" -> "Show Logs" to export Crash Report that name with Scrcpy.

Or, if you have no Xcode installed, you can follow these instructions to export Crash Report to me:

> For Mac OS X:
>
> Connect the iPad or iPhone to the Mac and sync it as usual
> Hit Command+Shift+G and navigate to ~/Library/Logs/CrashReporter/MobileDevice/
> For those with multiple iOS devices, select the proper device that you want to retrieve the crash log from
> Look for files with the app name you want the crash reports from

**Comment by ZhangTianrong** [comment]
Is [this](https://1drv.ms/u/s!Ah7B82t6Uj6F50dgEVlujdHLifOJ?e=ZoIK6E) the log you are looking for? It’s in the `retired` folder though. There are no up-to-date cash log in the parent folder.

**Comment by wsvn53** [comment]
Thanks for your crash logs, I'm trying to fix this crash, can you try this version agian. 
[Scrcpy.ipa.zip](https://github.com/wsvn53/scrcpy-ios/files/7827793/Scrcpy.ipa.zip)

**Comment by ZhangTianrong** [comment]
Despite a pretty long wait, the stream is finally started successfully. The video quality is quite bad compared to what I see on a Windows machine. Since decoding is using hw acceleration, maybe it’s because it’s using a different bitrate and encoder? But anyway, thank you for keeping getting back to me and now it’s at least running.

**Comment by wsvn53** [comment]
> 

Yes, you can try a higher bitrate, eg. 6M 8M will get better video quality:
![image](https://user-images.githubusercontent.com/912204/148523093-ac2101c9-9c9f-4afe-b343-73f229e7b161.png)

HW acceleration is only used for decoding video with lower cpu usage and lower energy consumption.

**Comment by ZhangTianrong** [comment]
Thank you, by setting a smaller max size and higher bitrate, the video quality is much better. I was actually speaking of encoder, wondering if it is possible that the android device being controlled isn't making use of its hardware encoder. But when I tested with my conventional Windows setup, the CPU usage is more or less the same (it's a TV box with quite limited computing resources), so I guess that shouldn't be the case. The only thing that I am still concerning about is the long wait time before the stream start. It is taking over a minute before the screen shows up but after that everything is smooth with pretty low latency. I will also try out some different SSH server tomorrow to see if the fix for temp folder generalize well.

**Comment by wsvn53** [comment]
The PC/Mac/Linux version of Scrcpy and the iOS version almost using the same scrcpy-server jar, which is pushed to android phone everytime to encode screenshot stream. So you can check the source code of scrcpy server encoder https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java 

The connection time you have metioned is about a minute, maybe bad network? You can try to ssh into this server to see how much time consumed. Typically, it only needs few seconds to see the screen.
